name = "Bapanada"
author = "Mercy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f47a006012fa50932206a833b1f0b99fcf6b60bbf182f555ec8f3c7e3f8de04"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
