name = "Bapanada"
author = "Mercy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52df6f2bf3214a4283af7988128616f20481ac40f0a348c0e0dfb0a49bc8ffe9"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
